### ISSUE TITLE
Nicely format SRA, MG-RAST, and iMicrobe metadata

### ISSUE THREAD

**Issue by ArwaAbbas** [louiejtaylor/grabseqs#22]

**Comment by louiejtaylor** [comment]
- [ ] MG-RAST
 - [ ] iMicrobe

**Comment by louiejtaylor** [comment]
Related...agglomerate metadata from the same run. For example:

    grabseqs sra SRP####### SRR########

makes two metadata files, and probably should only make one.

**Comment by louiejtaylor** [comment]
Idea for doing this better--rather than passing `-m` as a flag, pass the metadata filename to `-m`. This solves the issue of what filename to use if you have a bunch of stuff
