### ISSUE TITLE
fasterq-dump error:

### ISSUE THREAD

**Issue by EisenRa** [louiejtaylor/grabseqs#25]
Thanks for making this tool, it's a real time saver!

I'm attempting to download a list of SRS accessions, which, at the start was working fine, but after a few hours has been consistently erroring:

`downloading SRR2192724 using fasterq-dump
2019-04-09T00:56:16 fasterq-dump.2.9.1 err: storage exhausted while creating directory within file system module - error with https open 'https://sra-download.ncbi.nlm.nih.gov/traces/sra33/SRR/002141/SRR2192724'
2019-04-09T00:56:16 fasterq-dump.2.9.1 err: **invalid accession 'SRR2192724'**
pigz: skipping: SRS475922/SRR2192724*fastq does not exist
SRA download for acc SRR2192724 failed, retrying 0 more times.
Traceback (most recent call last):
  File "/localscratch/EisenRa/miniconda2/bin/grabseqs", line 11, in <module>
    sys.exit(main())
  File "/localscratch/EisenRa/miniconda2/lib/python3.6/site-packages/grabseqslib/__init__.py", line 59, in main
    run_fasterq_dump(acc, args.retries, args.threads, args.outdir, args.force, args.fastqdump)
  File "/localscratch/EisenRa/miniconda2/lib/python3.6/site-packages/grabseqslib/sra.py", line 114, in run_fasterq_dump
    raise Exception("download for "+acc+" failed. fast(er)q-dump returned "+str(retcode)+", pigz returned "+str(rgzip)+".")
Exception: download for SRR2192724 failed. fast(er)q-dump returned 0, pigz returned 0.`

It claims invalid accession, but the SRA file link is downloadable with wget. Is this some kind of cache error? I've got enough space on the disk.

Commands ran:
`while read SRS; do grabseqs sra -t 50 -m -o $SRS -r 3 $SRS; done < SRS.txt`
Where SRS.txt = a list of SRS accessions, one per line.

Best wishes,
Raphael

**Comment by louiejtaylor** [comment]
Hi Raphael, I'm glad it's been useful (and that it works for someone outside our lab)! I haven't seen that particular error before, but I have a few thoughts for things you might try. 

Caching is always a good guess--NCBI loves to cache the SRA data, and caching is on by default (and the cache is basically all of your sequences, which is not ideal). Have you turned it off using `vdb-config -i` as in the grabseqs readme? See [this link](https://github.com/ncbi/sra-tools/wiki/Toolkit-Configuration) for more info. If you did have caching turned on, I'd recommend removing the directory made by sra-toolkit...usually it's located at `~/ncbi`. My guess is that maybe this is the cause of the running-out-of-space error? I managed to download that particular SRR without error, so if that doesn't work please let me know and I'm happy to help debug further.

**Comment by EisenRa** [comment]
Hi Louie,

Thanks for the quick feedback.

I've had look, and the ~/ncbi folder is by default on a low space disk that was full ($HOME). I've turned it off as suggested and it's working fine!

Cheers,
Raphael

**Comment by louiejtaylor** [comment]
Sweet, I'm glad it worked!
