### ISSUE TITLE
Version 0.5.0 breaks numpy

### ISSUE THREAD

**Issue by louiejtaylor** [louiejtaylor/grabseqs#29]
Multiple errors incl

    module 'numpy' has no attribute '__version__'

and

    ImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['/.../miniconda2/envs/sunbeam/lib/python3.6/site-packages/numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.

I suspect this is due to duplicated requirements/dependencies between `setup.py` (pip) and other packages grabbing numpy in their `environment.yml` (conda) although I'm not sure what the correct workaround is for this...

**Comment by louiejtaylor** [comment]
A workaround (at least for [Sunbeam](https://github.com/sunbeam-labs/sunbeam)) is to pin to v0.3.4....which already appears to be the case. I guess my local version was behind. Keeping this open for additional testing

**Comment by ressy** [comment]
I just now made an empty environment and did `conda install -c louiejtaylor -c bioconda grabseqs` and grabseqs and numpy combo I ended up with (versions 0.5.0 and 1.16.2) seem happy, for what that's worth.

**Comment by louiejtaylor** [comment]
Thanks for looking at this, Jesse! I thought the issue was related to installing numpy via pip and conda, but it worked fine (`conda install -c louiejtaylor -c bioconda grabseqs` installed the same versions you saw and `import numpy` threw no errors).

The numpy version installed with Sunbeam is different (1.12.1)--so that might be the source of the problem. I can troubleshoot it later; this is a low-priority problem that will likely only affect me so don't worry about spending more of your valuable time tracking it down!
