### ISSUE TITLE
Not compatible with Python 3.7?

### ISSUE THREAD

**Issue by dutchscientist** [louiejtaylor/grabseqs#38]
Can only install it in Python 3.6, but standard conda is already on Python 3.7. Is there a reason for this restriction?

**Comment by louiejtaylor** [comment]
Thanks for the issue! I haven't been able to build successfully for Python 3.7 and am not sure why, but this is good motivation to figure it out.

**Comment by dutchscientist** [comment]
No worries, I have installed it using a Conda environment for 3.6. But would be good to add a warning to the descriptor?

conda create -n py36 python=3.6
conda activate py36
conda install [etc ect]
conda deactivate

And do "conda activate py36" before every run, and "conda deactivate" afterwards

**Comment by louiejtaylor** [comment]
Yeah, that's a good idea. Hopefully I'll figure this out quickly but until then a warning is good.

**Comment by louiejtaylor** [comment]
Grabseqs itself works fine in Python 3.7...there's something wonky going on during the conda-build process where Conda seems to be adding a requirement for Python 3.6 and I can't seem to find where. I'll track it down though!
