### ISSUE TITLE
error handling when sra accession doesn't exist / doesn't return runs

### ISSUE THREAD

**Issue by a-h-b** [louiejtaylor/grabseqs#51]
Hi -
when I run grabseqs with a project identifier that has no links to any runs
(example: 
grabseqs sra -l PRJNAXXXXX)

, grabseqs dies with 

> ValueError: 'Run' is not in list 

Rightly so, because list.index() raises a ValueError when there is no matching item (see e.g. https://docs.python.org/3/tutorial/datastructures.html)

solution:
in line 98 of sra.py the error should be caught with 
`except ValueError: 
    raise ValueError("Could not find samples for accession: "+pacc+". If this accession number is valid, try re-running.")`

Best wishes -
Anna

**Comment by louiejtaylor** [comment]
Thanks very much for the issue! This is definitely a case that should be handled (and tested). Thanks also for proposing a solution.
